version: '3.8'

services:
  # Service application (Flask)
  app:
    build:
      context: ./flask
    container_name: flask-app
    restart: always
    environment:
      - FLASK_ENV=production
    volumes:
      - flask_data:/app/data
      - flask_logs:/app/logs
    networks:
      - app-network
    ports:
      - "5000"  # Exposé uniquement sur le réseau interne

  # Service web (Nginx)
  web:
    build:
      context: ./nginx
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"  # Exposé sur le port 80 de l'hôte
    volumes:
      - ./nginx/static:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
      - app  # Dépend du service app, donc démarrera après lui
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  flask_data:
  flask_logs: 